baseURL = "https://words.codes/"
languageCode = "sk-sk"
DefaultContentLanguage = "sk"
title = "Words & Codes"
theme = "words&codes"
enableRobotsTXT = "true"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  tag = "tags"